[package]
name = "SimpleRT"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
ordered-float = "1.0.1"
rand = "0.8.4"
oorandom = "11.1.3"